create schema if not exists src_schema;
create schema if not exists dwh_schema;

-- source tables
create table if not exists src_schema.country
(
    country_code varchar(10) primary key,
    country_name varchar(100),
    region varchar(100)
);

create table if not exists src_schema.customer
(
    customer_id varchar(20) primary key,
    customer_name varchar(100),
    country_code varchar(10),
    customer_type varchar(50)
);

create table if not exists src_schema.product
(
    product_id varchar(20) primary key,
    product_name varchar(100),
    category varchar(100),
    standard_price numeric(12,2)
);

create table if not exists src_schema.sales_transactions
(
    transaction_id varchar(20) primary key,
    transaction_date date,
    customer_id varchar(20),
    product_id varchar(20),
    quantity integer,
    unit_price numeric(12,2),
    total_amount numeric(12,2),
    payment_mode varchar(50)
);

-- target sequences
create sequence if not exists dwh_schema.country_dim_seq start 1;
create sequence if not exists dwh_schema.customer_dim_seq start 1;
create sequence if not exists dwh_schema.product_dim_seq start 1;
create sequence if not exists dwh_schema.sales_trans_fact_seq start 1;

-- target tables
create table if not exists dwh_schema.country_dim
(
    country_id numeric primary key,
    country_code varchar(10) unique,
    country_name varchar(100),
    region varchar(100)
);

create table if not exists dwh_schema.customer_dim
(
    customer_id varchar(20) primary key,
    customer_name varchar(100),
    country_code varchar(10),
    customer_type varchar(50)
);

create table if not exists dwh_schema.product_dim
(
    product_id varchar(20) primary key,
    product_name varchar(100),
    category varchar(100),
    standard_price numeric(12,2)
);

create table if not exists dwh_schema.date_dim
(
    date_wid integer primary key,
    date_value date unique,
    day integer,
    month integer,
    month_name varchar(10),
    quarter varchar(2),
    year integer,
    day_of_week integer,
    day_name varchar(10),
    week_number integer,
    is_weekend char(1),
    is_holiday char(1),
    wh_insert_dt timestamp
);

create table if not exists dwh_schema."Sales_Trans_Fact"
(
    transaction_id varchar(20) primary key,
    transaction_date date,
    customer_id varchar(20),
    product_id varchar(20),
    quantity integer,
    unit_price numeric(12,2),
    total_amount numeric(12,2),
    payment_mode varchar(50)
);

-- source view
create or replace view src_schema.data_view as
select
    s.transaction_id,
    s.transaction_date,
    s.customer_id,
    c.customer_name,
    c.country_code,
    c.customer_type,
    p.product_id,
    p.product_name,
    p.category,
    p.standard_price,
    s.quantity,
    s.unit_price,
    s.total_amount,
    s.payment_mode,
    co.country_name,
    co.region
from src_schema.sales_transactions s
left join src_schema.customer c
    on s.customer_id = c.customer_id
left join src_schema.product p
    on s.product_id = p.product_id
left join src_schema.country co
    on c.country_code = co.country_code;

-- select access on source
do $$
begin
    if not exists (
        select 1
        from pg_roles
        where rolname = 'dwh_user'
    ) then
        create role dwh_user login password 'dwh_user_123';
    end if;
end $$;
grant usage on schema src_schema to dwh_user;
grant select on all tables in schema src_schema to dwh_user;
alter default privileges in schema src_schema grant select on tables to dwh_user;

-- audit table
create table if not exists dwh_schema.data_load_audit
(
    control_id bigint generated by default as identity primary key,
    source_name varchar(100),
    target_table varchar(100),
    record_count numeric,
    status varchar(30),
    load_start_time timestamp,
    load_end_time timestamp,
    inserted_date timestamp default current_timestamp
);

-- error table
create table if not exists dwh_schema.error_log
(
    log_id bigint generated by default as identity primary key,
    source_name varchar(100),
    error_msg varchar(4000),
    created_date timestamp default current_timestamp
);

create or replace procedure dwh_schema.log_error
(
    p_source_name varchar(100),
    p_error_msg varchar(4000)
)
language plpgsql
as $$
begin
    insert into dwh_schema.error_log
    (
        source_name,
        error_msg,
        created_date
    )
    values
    (
        p_source_name,
        p_error_msg,
        current_timestamp
    );
end;
$$;

create or replace procedure dwh_schema.log_data_load_audit
(
    p_source_name varchar(100),
    p_target_table varchar(100),
    p_status varchar(30),
    p_record_count numeric,
    p_load_start_time timestamp,
    p_load_end_time timestamp
)
language plpgsql
as $$
begin
    insert into dwh_schema.data_load_audit
    (
        source_name,
        target_table,
        record_count,
        status,
        load_start_time,
        load_end_time
    )
    values
    (
        p_source_name,
        p_target_table,
        p_record_count,
        p_status,
        p_load_start_time,
        p_load_end_time
    );
end;
$$;

create or replace procedure dwh_schema.load_dwh_truncate()
language plpgsql
as $$
declare
    v_start_time timestamp;
    v_end_time timestamp;
    v_record_count numeric;
begin
    begin
        truncate table dwh_schema."Sales_Trans_Fact";
        truncate table dwh_schema.date_dim;
        truncate table dwh_schema.product_dim;
        truncate table dwh_schema.customer_dim;
        truncate table dwh_schema.country_dim;

        alter sequence dwh_schema.country_dim_seq restart with 1;
        alter sequence dwh_schema.customer_dim_seq restart with 1;
        alter sequence dwh_schema.product_dim_seq restart with 1;
        alter sequence dwh_schema.sales_trans_fact_seq restart with 1;

        v_start_time := current_timestamp;
        insert into dwh_schema.country_dim
        (
            country_id,
            country_code,
            country_name,
            region
        )
        select
            nextval('dwh_schema.country_dim_seq'),
            country_code,
            country_name,
            region
        from src_schema.country;
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.country','dwh_schema.country_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        insert into dwh_schema.customer_dim
        (
            customer_id,
            customer_name,
            country_code,
            customer_type
        )
        select
            customer_id,
            customer_name,
            country_code,
            customer_type
        from src_schema.customer;
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.customer','dwh_schema.customer_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        insert into dwh_schema.product_dim
        (
            product_id,
            product_name,
            category,
            standard_price
        )
        select
            product_id,
            product_name,
            category,
            standard_price
        from src_schema.product;
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.product','dwh_schema.product_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        insert into dwh_schema.date_dim
        (
            date_wid,
            date_value,
            day,
            month,
            month_name,
            quarter,
            year,
            day_of_week,
            day_name,
            week_number,
            is_weekend,
            is_holiday,
            wh_insert_dt
        )
        select
            to_char(dt, 'YYYYMMDD')::int,
            dt::date,
            extract(day from dt)::int,
            extract(month from dt)::int,
            to_char(dt, 'MON'),
            'Q' || extract(quarter from dt)::int,
            extract(year from dt)::int,
            extract(dow from dt)::int,
            to_char(dt, 'DAY'),
            to_char(dt, 'WW')::int,
            case
                when to_char(dt, 'DY') in ('SAT','SUN') then 'Y'
                else 'N'
            end,
            'N',
            current_timestamp
        from generate_series(date '2015-01-01', date '2030-12-31', interval '1 day') as dt;
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('SYSTEM_GENERATED','dwh_schema.date_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        insert into dwh_schema."Sales_Trans_Fact"
        (
            transaction_id,
            transaction_date,
            customer_id,
            product_id,
            quantity,
            unit_price,
            total_amount,
            payment_mode
        )
        select
            transaction_id,
            transaction_date,
            customer_id,
            product_id,
            quantity,
            unit_price,
            total_amount,
            payment_mode
        from src_schema.sales_transactions;
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.sales_transactions','dwh_schema.Sales_Trans_Fact','SUCCESS',v_record_count,v_start_time,v_end_time);

    exception
        when others then
            call dwh_schema.log_error('load_dwh_truncate', sqlerrm);
            raise;
    end;
end;
$$;

create or replace procedure dwh_schema.load_dwh_merge()
language plpgsql
as $$
declare
    v_start_time timestamp;
    v_end_time timestamp;
    v_record_count numeric;
begin
    begin
        v_start_time := current_timestamp;
        merge into dwh_schema.country_dim as tgt
        using src_schema.country as src
        on (tgt.country_code = src.country_code)
        when matched then
            update set
                country_name = src.country_name,
                region = src.region
        when not matched then
            insert
            (
                country_id,
                country_code,
                country_name,
                region
            )
            values
            (
                nextval('dwh_schema.country_dim_seq'),
                src.country_code,
                src.country_name,
                src.region
            );
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.country','dwh_schema.country_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        merge into dwh_schema.customer_dim as tgt
        using src_schema.customer as src
        on (tgt.customer_id = src.customer_id)
        when matched then
            update set
                customer_name = src.customer_name,
                country_code = src.country_code,
                customer_type = src.customer_type
        when not matched then
            insert
            (
                customer_id,
                customer_name,
                country_code,
                customer_type
            )
            values
            (
                src.customer_id,
                src.customer_name,
                src.country_code,
                src.customer_type
            );
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.customer','dwh_schema.customer_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        merge into dwh_schema.product_dim as tgt
        using src_schema.product as src
        on (tgt.product_id = src.product_id)
        when matched then
            update set
                product_name = src.product_name,
                category = src.category,
                standard_price = src.standard_price
        when not matched then
            insert
            (
                product_id,
                product_name,
                category,
                standard_price
            )
            values
            (
                src.product_id,
                src.product_name,
                src.category,
                src.standard_price
            );
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.product','dwh_schema.product_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        merge into dwh_schema.date_dim as tgt
        using (
            select
                to_char(dt, 'YYYYMMDD')::int as date_wid,
                dt::date as date_value,
                extract(day from dt)::int as day,
                extract(month from dt)::int as month,
                to_char(dt, 'MON') as month_name,
                'Q' || extract(quarter from dt)::int as quarter,
                extract(year from dt)::int as year,
                extract(dow from dt)::int as day_of_week,
                to_char(dt, 'DAY') as day_name,
                to_char(dt, 'WW')::int as week_number,
                case
                    when to_char(dt, 'DY') in ('SAT','SUN') then 'Y'
                    else 'N'
                end as is_weekend,
                'N' as is_holiday,
                current_timestamp as wh_insert_dt
            from generate_series(date '2015-01-01', date '2030-12-31', interval '1 day') as dt
        ) as src
        on (tgt.date_wid = src.date_wid)
        when matched then
            update set
                date_value = src.date_value,
                day = src.day,
                month = src.month,
                month_name = src.month_name,
                quarter = src.quarter,
                year = src.year,
                day_of_week = src.day_of_week,
                day_name = src.day_name,
                week_number = src.week_number,
                is_weekend = src.is_weekend,
                is_holiday = src.is_holiday,
                wh_insert_dt = src.wh_insert_dt
        when not matched then
            insert
            (
                date_wid,
                date_value,
                day,
                month,
                month_name,
                quarter,
                year,
                day_of_week,
                day_name,
                week_number,
                is_weekend,
                is_holiday,
                wh_insert_dt
            )
            values
            (
                src.date_wid,
                src.date_value,
                src.day,
                src.month,
                src.month_name,
                src.quarter,
                src.year,
                src.day_of_week,
                src.day_name,
                src.week_number,
                src.is_weekend,
                src.is_holiday,
                src.wh_insert_dt
            );
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('SYSTEM_GENERATED','dwh_schema.date_dim','SUCCESS',v_record_count,v_start_time,v_end_time);

        v_start_time := current_timestamp;
        merge into dwh_schema."Sales_Trans_Fact" as tgt
        using src_schema.sales_transactions as src
        on (tgt.transaction_id = src.transaction_id)
        when matched then
            update set
                transaction_date = src.transaction_date,
                customer_id = src.customer_id,
                product_id = src.product_id,
                quantity = src.quantity,
                unit_price = src.unit_price,
                total_amount = src.total_amount,
                payment_mode = src.payment_mode
        when not matched then
            insert
            (
                transaction_id,
                transaction_date,
                customer_id,
                product_id,
                quantity,
                unit_price,
                total_amount,
                payment_mode
            )
            values
            (
                src.transaction_id,
                src.transaction_date,
                src.customer_id,
                src.product_id,
                src.quantity,
                src.unit_price,
                src.total_amount,
                src.payment_mode
            );
        get diagnostics v_record_count = row_count;
        v_end_time := current_timestamp;
        call dwh_schema.log_data_load_audit('src_schema.sales_transactions','dwh_schema.Sales_Trans_Fact','SUCCESS',v_record_count,v_start_time,v_end_time);

    exception
        when others then
            call dwh_schema.log_error('load_dwh_merge', sqlerrm);
            raise;
    end;
end;
$$;

create or replace procedure dwh_schema.run_all_procedures()
language plpgsql
as $$
begin
    begin
        call dwh_schema.load_dwh_truncate();
        call dwh_schema.load_dwh_merge();
    exception
        when others then
            call dwh_schema.log_error('run_all_procedures', sqlerrm);
            raise;
    end;
end;
$$;
